# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

include:
  - board: xiao_ble//zmk
    shield: klor_dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart #zmk-usb-logging
    
  - board: nice_nano//zmk
    shield: klor_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    
  - board: nice_nano//zmk
    shield: klor_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    
  - board: nice_nano//zmk
    shield: settings_reset
    
  - board: xiao_ble//zmk
    shield: settings_reset
    #cmake-args: -DCONFIG_MPU_ALLOW_FLASH_WRITE=y -DCONFIG_FLASH=y -DCONFIG_FLASH_PAGE_LAYOUT=y -DCONFIG_FLASH_MAP=y -DCONFIG_NVS=y -DCONFIG_SETTINGS_NVS=y
